### ISSUE TITLE
Design updates for mobile

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/website#101]
I've noticed a few rough edges when viewing the website on my iPhone.

### Home
- [ ] "US Historical Data" and "Most Recent Data" in the header wrap onto two lines.
- [x] The "In the press" logos stretch the width but the list below wraps much earlier, causing the logos to have a big overhang.
- [x] Footer links stack vertically quite a bit. Maybe fine but looks a bit odd.

### Most recent data
- [x] "Pos + neg" title in US totals table wraps
- [x] Below each state the "Grade - Last updated - Last checked" display wraps. Maybe stack?

I'll stop here but when we have resources this could use a pass.

**Comment by schwartzadev** [comment]
#106 fixes:

- [x] "Pos + neg" title in US totals table wraps
- [x] Below each state the "Grade - Last updated - Last checked" display wraps. Maybe stack?

The grade/last updated/last checked display is now stacked.

**Comment by schwartzadev** [comment]
It looks like the three `Home` issues are still open

**Comment by kissane** [comment]
We are working on a full design/markup rescue mission, a lot of this is going to be open through this week so that we're able to do that work thoroughly instead of gopher-whacking things individually. The one piece we have to address in parallel to the overall design/CSS/markup overhaul is that we need to rework navigation items, but the other rough edges are going to stay rough for a bit.
