### ISSUE TITLE
Surface downloadable CSVs

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#1033]
In order to make our CSVs more accessible, let's:

- [x] Update the preamble of the data page:
> We update all the data each day between 4pm and 5pm EDT. You can also get the dataset as a [spreadsheet](), [CSV files](), and an [API]().
- [x] Add a link to `/data/download` in the preamble of the `/api` page

## Create a new page at `/data/download` that:

- [x] Shows similar information about caveats that we use in the API page.
- [x] Lists US and state download links
- [x] Displays all the fields, along with descriptions, like we do with the API page

### Page structure:

- US history
  - Download all history data
  - Field descriptions (collapsible)
- State history
  - Download State data
    - Field descriptions (collapsible)
    - Download all states (`/api/v1/states/daily.csv`)
    - Download single state (collapsible)
      - List all state files (`/api/v1/states/[state]/daily.csv`)

## Discussion:

I think the [API explorer](https://covidtracking.com/api) could still work well for downloadable CSV files, but I could be wrong. FYI all the fields and descriptions are defined by the API and automagically available, so reformatting the display is easy.

We *could* provide a list of all the downloadable CSV files by state (the daily history). I don't think linking off to the `api/v1/states/[state]/[date].csv` files makes sense.

**Comment by amandafrench** [comment]
I think the word “spreadsheet” should be replaced with “read-only spreadsheet” or similar maybe — and maybe make the downloadable CSV files the first thing in the sentence.

**Comment by kissane** [comment]
Maaaaaybe

> We update all the data each day between 4pm and 5pm EDT. You can also [see the dataset as a spreadsheet](), [download CSV files for everything we track](), or use an [API]().

**Comment by kissane** [comment]
> We update all the data each day between 4pm and 5pm EDT. You can also [download CSV files for everything we track](), [see the dataset as a spreadsheet](), or use our [APIs]().

is "APIs" correct

**Comment by amandafrench** [comment]
I myself would rather like a list of per-state downloadable CSVs on a new Download page since I’m mainly interested in N.C.

**Comment by amandafrench** [comment]
And am not really an API user

**Comment by kevee** [comment]
I think the API page is fine, but we should make the download page it's own thing. I updated the page structure accordingly.

**Comment by amandafrench** [comment]
Love the preview I saw! One question: are the national and state-level field descriptions going to be automatically updatable? Because if not I almost think that putting links there to the API or wherever they are primarily maintained might be better. 

Also, I'd suggest these changes to headers in Contentful: 

* "US History" --> "US Data" (or possibly "US COVID-19 Data")
* "Download all history data" --> "Download all available US data"  
* "State History" --> "State Data" (or possibly "State COVID-19 Data")
* "Download all states" --> "Download all available data for all states" 
* "Download single state" --> "Download all available data for a single state" 

There might be better ways to convey the idea of "historical data" or "time series" or "since March 7, 2020" or what have you: open to suggestions. Ping @kissane.

**Comment by amandafrench** [comment]
Technically we should probably say "states and territories" everywhere as well

**Comment by kevee** [comment]
All the fields in there are automatically updated when our API changes.

**Comment by scandycuz** [comment]
Hi @amandafrench, I'm happy to answer what I can. 

The field descriptions are actually dynamically generated from the same source that the API page uses. 

I'm happy to make any language changees. The headers are currently hard coded, but I can definitely update it so that they come from contentful, which I will

**Comment by kevee** [comment]
Merged the PR and updated content snippets. Closing.

**Comment by amandafrench** [comment]
Love it. Many emails forestalled.
