### ISSUE TITLE
Search bar won't close

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1034]
## Replicate
Checkout the `feature/nav-refresh` branch (see #1024 )
1. Open the search bar
2. Do not enter content into the `<input>` field
3. Click on the search icon

## Expected behavior
The search bar closes

## Actual Behavior
The search bar closes on mouse down, and then re-opens on mouse up

**Comment by scandycuz** [comment]
Hi, thanks again for adding me to the #website channel on Slack. It looks like this bug was caused by conflicting click and blur props on the search button and search input. When the search button was clicked it triggered both the `onBlur` prop of the search input and the `onClick` handler of the search button, causing `autocompleteHasFocus` to be toggled twice.

I had some trouble solving it while leaving the toggle functionality, and ended up implementing 'setAutocompleteFocus' action with an explicit status instead. I also removed the `onBlur` prop from the search input and instead toggled 'autocompleteHasFocus' off when there is a click outside the search bar.

I wasn't able to push to the repository, of course, but here is some of the code:

```
function handleOutsideClick(e) {
    if (searchRef.current && searchRef.current.contains(e.target)) {
      return
    }

    searchDispatch({
      type: 'setAutocompleteFocus',
      autocompleteHasFocus: false,
    })

    window.removeEventListener('click', handleOutsideClick)
  }

  function toggleFocusOrQuery() {
    if (autocompleteHasFocus && query) {
      navigate(`/search?q=${query}`)
    }

    searchDispatch({
      type: 'setAutocompleteFocus',
      autocompleteHasFocus: !autocompleteHasFocus,
    })

    window.addEventListener('click', handleOutsideClick)
  }
```
