### ISSUE TITLE
feat: embedded docs & sheets on site?

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#1248]
So I know it's very 2007, just like #916, but in trying to get my head around all the documentation we should be doing I keep thinking about how much research we do every day and how much of it is in Google Sheets and Docs and how much faster and better we would be at keeping the public up to date if we could just embed those documents on the website. We could put up the PCL research sheet, we could put up the new daily patch notes, maybe even the FAQ. Is there any corner of the site where we could do some ugly things like that? I know too that we probably want editorial oversight, but what with the speed with which things change, and everyone being overloaded, and our highly wonderful and collaborative methods of working (which mean that we spend a lot of time discussing things), it feels like the speed of real-time updating in something like an embed is important.

**Comment by kevee** [comment]
We can [pull data from docs directly](https://www.gatsbyjs.org/packages/gatsby-source-google-docs/) and make pages out of them, but I'm sure that is a potential rabbit hole of other problems (no explicit published version, what with the formatting, etc)

I think a lot of this is a process question rather than a specific technical issue tho.

**Comment by amandafrench** [comment]
Yes, you're right, not really issue worthy. Issue in haste, repent at leisure.
