### ISSUE TITLE
Summary charts have overlapping x-axis date

### ISSUE THREAD

**Issue by goleary** [COVID19Tracking/website#1251]
With only 10 days between the first of July & July 11th the dates overlap. I tested it before and I think the 15th was the sweet spot.
![image](https://user-images.githubusercontent.com/16123225/87236943-8adccb00-c3a4-11ea-96d3-ab819154629b.png)

**Comment by schwartzadev** [comment]
I'm not sure which solution to choose here. We could:

1. Do nothing and accept this type of clash
2. Keep the same data points (the first of each month and the latest data) but re-arrange them to not overlap
3. Stop indicating the date from the latest data on the x axis and keep the first of the month markings
4. Keep the latest data and move the markings from the first of each month to the fifteenth of each month
5. Do something else

Relatedly, I think we should use a `m/d` (like `5/1`) date format instead of our current `M d` (like `May 1`) format, since these values will only become more squished as time passes.

**Comment by kevee** [comment]
The month name should be in the chart per our style guide:

> Always use month names, not just numerical dates. This avoids confusion for non-US readers: May 3, not 5/3

I agree on just changing the cut-off date to 15, this "last date" on the chart was there to just prevent folks from seeing a long space with no date when we were almost to the end of the month

**Comment by goleary** [comment]
k, i'll update and submit a PR with the cutoff as 15.
