### ISSUE TITLE
Support multiple return links

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1302]
We'll need to be able to navigate to multiple levels for our state subpages. (Such as `Arizona Tests`) i.e.
```Our Data > Arizona```
instead of
`Arizona`

**Comment by tealtan** [comment]
Mockup is here!
https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=1042%3A10513

(It uses the existing caret from the nav, except pointing to the right rather than pointing downwards. Happy to provide a new icon if that helps!)

**Comment by tealtan** [comment]
Thinking about it a bit further, I think we can even bring blog posts into the fold:
https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=1667%3A15507

The other mockups on this page just show a few more variations of the design.

Basically, I think of this as:
- Getting rid of the left arrow, in all cases
- Multiple parent pages in the breadcrumb are separated by a caret
- For blog posts, they have a "parent" that consists of all the categories a post is tagged with, and each category is separated by a dot separator (similar to the press section on the homepage)
- On mobile, the breadcrumb goes off the viewport (and is scrollable horizontally) rather than wrapping. I think maybe the breadcrumb ought to wrap starting at the `viewport-lg` breakpoint (which is when header content is inset)

**Comment by tealtan** [comment]
Thinking about it a bit further, I think we can even bring blog posts into the fold:
https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=1667%3A15507

The other mockups on this page just show a few more variations of the design.

To sum up the key points:
- Getting rid of the left arrow, in all cases
- Multiple parent pages in the breadcrumb are separated by a caret
- For blog posts, they have a "parent" that consists of all the categories a post is tagged with, and each category is separated by a dot separator (similar to the press section on the homepage)
- On mobile, the breadcrumb goes off the viewport (and is scrollable horizontally) rather than wrapping. I think maybe the breadcrumb ought to wrap starting at the `viewport-lg` breakpoint

**Comment by schwartzadev** [comment]
Awesome, can do!

Another content item:
- [ ] Use title case for all return links

(Allen, I deleted your duplicate comment -- it's nothing nefarious!)

**Comment by schwartzadev** [comment]
@tealtan what did you have in mind for the hover styles? Should we use the default dark background link styles or something else?

**Comment by tealtan** [comment]
I’d say they can be the same as the return links they’re replacing – so, underlining on hover.
