### ISSUE TITLE
chore (docs): Can't put Data FAQ into subnav on About Data

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#1323]
This is probably a Contentful issue, but I've had a lot of trouble with the page subnav on [About Data](https://covidtracking.com/about-data). It is currently missing the Data FAQ page even though that page and its navigation link have been associated with the About Data Navigation Group. Wondering if the group is limited to five entries or something.

**Comment by schwartzadev** [comment]
This does not seem to be a contentful issue, but a code one!

The header tabs exclude the first result from the contentful navigation links, which in this case is the `Data FAQ` item.

see: `navigation.slice(navigation.length * -1 + 1)`
(`sub-navigation.js:9`)

This is because we want to include a nav link that points to the nav group to be the first dropdown item:

![image](https://user-images.githubusercontent.com/18607205/89828693-9f80c000-db16-11ea-8f7d-25bbb2776466.png)
(note that "data by state" links to the same place as "our data")

...but we don't want that link in the header tabs (nominally because it would just link to the current page):
![image](https://user-images.githubusercontent.com/18607205/89828726-ac9daf00-db16-11ea-826b-427c5ce5d111.png)
(note that "data by state" is missing)

To remedy this, we could either re-order the About nav group in CF such that:
* the Data FAQ item is not the first item
* "How to use the data" is the first item (because it links to the group itself)

Alternatively, we could use a different (maybe a more intuitive?) system for nav links that link to a nav group, and implement it in the code.

Hopefully this is helpful!

**Comment by kevee** [comment]
I moved "How to use the data" up top on the navigation and the issue has ben fixed. I know that it's not the most intuitive system, but it is simple!

**Comment by schwartzadev** [comment]
Thanks @kevee!

**Comment by amandafrench** [comment]
OMG this was driving me nuts. Simple when you know. Thanks for explaining and fixing!
