### ISSUE TITLE
Fix "Get better data" scrolling issue

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1675]
Right now, when users click from the main `data` page to the `get-better-data` page, the page automatically scrolls to the end of the page.

I think this is because gatsby is retaining the `data` page's scrolling position, but I am not at all sure.

### Expected behavior

1. Navigate to https://covidtracking.com/data
2. Click on "Help us get better data." under American Samoa
3. Navigate to https://covidtracking.com/race/get-better-data#AS scrolled to the _top_ of the page

### Actual behavior

* Steps 1-2 from above
* Navigate to https://covidtracking.com/race/get-better-data#AS scrolled to the _bottom_ of the page

Builds on #1651. Completes #1643.

**Comment by gitjeff05** [comment]
I see this issue as well. Looking into it, when transitioning from:

`/data/#state-as` -> `/race/get-better-data#AS`

the scroll position is near the bottom of the page. It feels as if gatsby or the browser are not recognizing `/race/get-better-data` as a new route and are respecting the previous scroll position. To dig in further, I attempted to verify a few things: 

 - Does [onRouteUpdate](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#onRouteUpdate) fire? Yes it does. So, gatsby does recognize `/race/get-better-data` as a new route. 

 - Can we employ [shouldUpdateScroll](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/#recommendations-for-programmatic-in-app-navigation) to override the scroll position? No, because mysteriously, it does not even fire on this route change. The docs do not explain when this event should fire. Since it takes arguments `routerProps` and `prevRouterProps`, I assume that it should fire on every route change.

 - Since the documentation for [in-route navigation with a hash](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/#recommendations-for-programmatic-in-app-navigation) states that "neither `<Link>` nor `navigate` can be used with a hash", does the suggested function `navigate` from `@reach/router` fix this? It does not appear to fix this issue.

 - Does using the plain old `<a>` tag fix this? Yes it does. However, you lose the prefetching magic that comes with `<Link />`

I'm happy to help here, but I'm not as familiar with gatsby's routing/prefetch as others. @kevee or @schwartzadev if any of the above arouse further suspicions, let me know and I can dig in.
