### ISSUE TITLE
Recovery count

### ISSUE THREAD

**Issue by Greg-Boggs** [COVID19Tracking/website#177]
Is there a feasible way to add recovery count to the API? I've gotten a couple of requests for it now.

**Comment by kevee** [comment]
Adding comment from duplicate issue #180 filed by @mortenbache:
Thank you for this brilliant data set.
Form Italian data sets I find it extremely useful to track recovered/discharged patients from hospitals, so you can get an overview of the current load on the hospitals. Otherwise you just sum up. I know it is not so useful now because no one is being discharged yet, but it will be.
Another useful stat is "intensive therapy" cases.
I have made some excel dashboards that show how it can be useful
https://github.com/mortenbache/COVID-19-Excel-dashboards

**Comment by watplatt** [comment]
If you want to do modeling, in order to extract active infections, you have to subtract recovered+deceased from the cumulative positives.  Without recovered counts, this data isn't very useful for modeling (e.g. SEIR).

**Comment by Greg-Boggs** [comment]
Hospital load would be really nice to see as well which could be easily calculated once we have recovered data!

I got tired of squinting my eyes at Json, so I put this together for myself:

https://corona.gregboggs.com/

**Comment by watplatt** [comment]
I agree, Gregg-Boggs...  Hospitalizations w/ time would be really great!  Given that, compartmental models including hospitalizatons could break out rates of conversion to severe cases, rates of recovery for severe cases, etc.  Also on my wish list would be a bit on age structure (known risk group counts).  Knowing a hint of what state offices are like (NY is behind on reporting 'flu numbers longer each week... and I have friends in contact with similar in one other foreign nation), they are normally understaffed and overwhelmed now.  Nobody is thinking of modeling as a way to help make policy decisions, or to extract rates like incubation to infectious state (that may include some pre-clinicals), recovery as non-infectious, etc - all of which may help inform expectations about clinical treatments.  So reporting these numbers has low priority.  Some don't keep time series.  :(

**Comment by schwartzadev** [comment]
This is in the works..stay tuned :+1:

**Comment by schwartzadev** [comment]
#221 adds hospitalization numbers. I think we'll add new numbers to the website as we collect them and make them public on the spreadsheet.
