### ISSUE TITLE
Test Netlify CMS in new stack

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#241]

**Comment by kevee** [comment]
@kissane  - I sent you an invite to a separate Netlify login for testing the Netlify CMS. Any changes you make there will [go to this repo ](https://github.com/kevee/Covid19Tracking-website/tree/gatsbyjs)(and not go live anywhere).

The only change is because the CMS doesn't support folders, you will see four sections:

- **Pages** - top-level pages
- **About the data** - Pages under `/about`
- **About the project** - Pages under `/project`
- **Snippets** - Content that is used for part of a page, like the preamble to the data page

**Comment by kevee** [comment]
Closing, we are using Contentful as of #271
