### ISSUE TITLE
Bug: Pages are missing outermost gutters around ~1100px

### ISSUE THREAD

**Issue by beep** [COVID19Tracking/website#320]
Around the 1080–1100px viewport range, certain layout components run flush up against the left and right edges of the browser window:

<img width="1128" alt="homepage" src="https://user-images.githubusercontent.com/124493/78167248-295ba680-741c-11ea-884f-0cc98705678e.png">
<img width="1112" alt="help page" src="https://user-images.githubusercontent.com/124493/78167450-80fa1200-741c-11ea-9817-2e40dd1e8366.png">
<img width="1109" alt="footer" src="https://user-images.githubusercontent.com/124493/78167479-8ce5d400-741c-11ea-87a5-2e963c986dc4.png">

**Comment by friej715** [comment]
I think this first media query is triggering at a smaller size than the max-width of the container. Maybe the media query should be at the $viewport-xl size (1200px)?

(Asking before editing, since futzing with breakpoints unprompted seems like a great way to fix the site!) 

<img width="197" alt="Screen Shot 2020-04-02 at 10 21 00 AM" src="https://user-images.githubusercontent.com/1028403/78260203-b4e04080-74cb-11ea-8b61-653f9d667516.png">
