### ISSUE TITLE
API: Improve docs on date and dateChecked field on states/daily

### ISSUE THREAD

**Issue by bibhas2** [COVID19Tracking/website#397]
In ``/api/v1/states/daily.json`` the ``date`` field is a number. Example:

```json
{
        "date": 20200320,
}
```

This is an unusual way to represent date. I suggest formatting it as a "MM/DD/yyyy" string format.

**Comment by jgulian** [comment]
Hello, I'd like to help, but I am having trouble finding the documentation where this is an issue. I found see the endpoints on the website, but it looks like the date field was removed. Is there documentation for api/v1/states/daily.json, and if so where is it? Sorry for being a bother, but I'd like to help out.

**Comment by schwartzadev** [comment]
Hey @jgulian -- not a bother at all, thanks for offering :smile: 

Right now the API docs live at: https://covidtracking.com/api/ on the website.

I _think_ that they're served by contentful, which means that they're not editable through this repo. (I think @kevee could confirm this)

I would _love_ to see our docs move to a more open platform -- maybe something like [readthedocs](https://readthedocs.org/)? What do you think @kevee ?

**Comment by jgulian** [comment]
Cool, that is the page I was looking at; I'm glad I wasn't being stupid. If you decide to move to readthedocs, I would be glad to help with that. Otherwise I'll look for other issues I can do.

**Comment by kevee** [comment]
We have it in Contentful now just because we are building out more things like Blogs and that platform is much easier for content editors.

I agree that it's nice for developers to have versioned docs with API changes, and if @webmasterkai wants to manage docs that way, we can manage API docs with just markdown files in the site. Gatsby can easily ingest the markdown file (or anything, really) and use it for the content of the API page.

On a broader note, there is a few people in the devops team starting to take on docs, so I suggest we wait to see what platform and format they decide to go with first.

**Comment by kevee** [comment]
Merged this into #385, closing.
