### ISSUE TITLE
small multiples axes and size 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#430]
*x-axis*
we need to fix the x-axis for the small multiples. the last ones a weird again :/ 

<img width="1296" alt="Screen Shot 2020-04-07 at 3 20 24 PM" src="https://user-images.githubusercontent.com/39416238/78710463-6673dd00-78e3-11ea-82c5-006a2edd1f10.png">

*y-axis*
let's add some breathing space between grid lines and tick values 
delete all values except for the first of every row 
change all grid lines to #b2bbbf 

*size*
let's also try to put 8 states per row? the graphic is very long now and it will be easier to compare the states with more per row. they can also be 50% tinier

*NY chart*
the spike in NY is cut off 

<img width="330" alt="Screen Shot 2020-04-07 at 3 29 33 PM" src="https://user-images.githubusercontent.com/39416238/78711198-9a033700-78e4-11ea-948e-d13e75f044f8.png">

**Comment by vijaysharwar** [comment]
Working on this.

**Comment by vijaysharwar** [comment]
@julialedur @jeremiak I'm not sure about the proposed solutions. I actually think the individual charts need to be _larger_, not smaller.

The biggest issue is the difference in scale between a state like NY and the majority other states with far lower testing numbers. If we increase the y-axis scaling to accommodate NY's overflow, you won't see *anything* on the vast majority of charts, because their test numbers are too low by comparison.

We could have a different X/Y scale per state, but that would make comparisons very difficult.

I think a better starting place might be one, taller state chart per row, which can solve issues of both X and Y axes (and work better on small/mobile screens).

From there, could consider additional improvements:
- Show/hide toggle on each chart (plus "show/hide all") to optionally reduce number of charts, compare smaller number at a time
- Toggles between linear and log scaling on y-axis; this would shrink the visual discrepancy between large and small number of tests (example at [https://www.coronaviruschart.com/](https://www.coronaviruschart.com/))

**Comment by jeremiak** [comment]
Ya, it definitely presents some challenges. I think we want to do something like this, where one or two of the big outliers just break through their chart so that they're still useful and the rest of the charts are still intelligible.

<img width="1199" alt="Screen Shot 2020-04-08 at 2 31 57 PM" src="https://user-images.githubusercontent.com/780941/78820452-d21e7e80-79a5-11ea-8bca-3eb7be0070ba.png">

Though I think this issue is more about X-axis dates overlapping in the small multiples. Regardless of how small the chart is, the axis labels shouldn't overlap each other and should probably be consistent across all the charts

**Comment by julialedur** [comment]
yeah, this is what we had in our previous page. in this case the fact that NY breaks through the chart is pretty interesting in itself. 

i like your idea for a toggle between scales. feel free to add a button at the top if you want. 
but the charts should be smaller, otherwise there's no point on making them small multiples. they should be comparable at the same time (or with very little scrolling).

**Comment by writenorman** [comment]
Small multiples is using a lot of real-estate to display very small amount of information.. perhaps one single large stacked area chart would be better suited for this purpose (normalize both test & positives by state population because some states [vermont/wyoming!!] are vast underpopulated )?

**Comment by vijaysharwar** [comment]
@jeremiak @julialedur please see PR https://github.com/COVID19Tracking/website/pull/449. I think this is an improvement, but does change the layout quite a bit (single column for small screens, two column for large).

In addition to improvements above, I think we could:
- Provide a UI to set number of columns (let user determine size of the charts depending on their comparison needs)
- Add a +/- UI to zoom in and out (potentially on individual charts, or all at once)

**Comment by writenorman** [comment]
Another suggestion for the Y axis would be instead of using cumulative.. use non-cumulative daily data with a moving average (informing the daily throughput showing ability of each state at ramping up testing capacity)

**Comment by vijaysharwar** [comment]
I like @writenorman's solutions, but sounds like more substantial changes than should be done through this issue. Might be good to take a step back and scope out the precise needs/functionality before reworking further...

**Comment by julialedur** [comment]
@vijaysharwar though this is a fairly exploratory viz, there are certain aspects that should be set by us, like number of columns. otherwise it just gets too confusing and impossible for us to get our point across. let's implement your toggle button for per capita numbers. that way we can show:
- how NY's raw numbers are incredibly high 
- the comparison between states and how normalizing for population makes a difference

they should be tiny tiny though as this is not supposed to be a detailed zoomed in graphic. like this: 

![example](https://user-images.githubusercontent.com/39416238/78838005-3d2a7e00-79c3-11ea-9092-90797b020155.jpg)

 it will be clearer once we add a tooltip.

**Comment by writenorman** [comment]
PR #513 adds gap on yAxis tick, and relocated the "See all data from..." href link.

The whole point of small-multiples format is for quick side-by-side comparison (fit as many as you can on a single screen, not suitable for small screens)  Another good metric is Test Coverage for each state:

This can be approximated by percent of positives rate of total tests administered;  Which could be further extended onto per capital basis by: (positive_cases) / (test administered per million people)

**Comment by vijaysharwar** [comment]
@writenorman please see comment in https://github.com/COVID19Tracking/website/pull/513#issuecomment-612661315.

We've already:

- Removed all ticks and made charts responsive in https://github.com/COVID19Tracking/website/pull/449
- Added a toggle to switch between total tests and per capita in https://github.com/COVID19Tracking/website/issues/479

I think this issue probably should've been closed already. cc @goleary @julialedur
