### ISSUE TITLE
feat: Contact form

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#520]
We need a contact form for answering questions. Requirements:

 

- [x] A page should live at `/contact` that pulls in content from Contentful snippets. I created a stunt copy one with the slug `contact-page`. You can see examples of using a snippet in `/src/pages/data/index.js` - there's a GraphQL query to grab a snippet from Contentful (query name `dataPreamble`), then we put it in the body of the page.
- [x]  Turn the arrow "Want to get involved?" sections of the homepage into reusable components
- [x]  Add one to the bottom of the page that links to `/contact/accessibility`, the text can be 
- [x]  "Report a problem with accessibility on the website."
- [x] Create a page a `/contact/accessibility`
- [x] Add a form with two fields, "What is your email address?" and "What accessibility problems are you experiencing?"
- [x] Make sure the `<form>` tag has the attribute `data-netlify="true"`
- [x] Implement [spam prevention from Netlify](https://docs.netlify.com/forms/spam-filters/#honeypot-field) on the form.

Once this is set up, we can use the Form in a deploy preview and test it in Slack.

**Comment by kevee** [comment]
@friej715 is on it!

**Comment by kissane** [comment]
Hello! This is amazing, @friej715 and @kevee! Here's some content stuff:

The COVID Tracking Project runs on the effort and diligence of hundreds of volunteers, and we welcome your contribution. Please take a moment to select the best way of contacting us with your question or comment so that we can address your message as quickly as possible.

### I think I found a problem in the data
To report an error in the data, please [open an issue in our issues repository](https://github.com/COVID19Tracking/issues/issues) on GitHub.  (You'll have to sign up for a free GitHub account to do this, but it's very quick and keeps your message from being lost in a giant pile of email.) 

### I found a bug on your website or want to request that you change something
To report a non-data bug or request a feature on our website, please [open an issue in our website respository](https://github.com/COVID19Tracking/website/issues) on GitHub. (You'll have to sign up for a free GitHub account to do this, but it's very quick and keeps your message from being lost in a giant pile of email.) 

### I need help using your data
Please [fill out our quick data-user intake form](https://docs.google.com/forms/u/2/d/e/1FAIpQLSflC3O2yzScMHWd1ISGrkuiLKv4Ihu97MSS9xnvjBQ9q1G2gg/viewform?usp=send_form) and we'll get you into the appropriate channel on our project Slack, where you can ask questions and get help from peers and project volunteers.

### I want to do something else
- What would you like to do? (dropdown, probably)
  - Volunteer on the project 
  - Interview someone on the project for a news story
  - Something else

**Comment by kissane** [comment]
(Only that final section should actually do form-to-mail/Slack/etc.)

**Comment by friej715** [comment]
Okay, I've been coding all day for work and am a bit bleary-eyed, but I believe [this](https://github.com/COVID19Tracking/website/compare/master...friej715:jane/contact?expand=1) includes just about everything we want. (I think I have some remaining CSS tweaks to make it @beep-aligned :D)

Could I get a gut-check to make sure the way I've structured the components etc. seems correct? (Also if you'd rather I just make PRs first and ask questions in that thread instead, I can do that too!)

**Comment by kevee** [comment]
@friej715 This is GREAT! I say do the PR!
