### ISSUE TITLE
state picker doesn't work on mobile (chrome android)

### ISSUE THREAD

**Issue by goleary** [COVID19Tracking/website#551]
the state picker doesn't work on mobile.

after having selected 'California':

![image](https://user-images.githubusercontent.com/16123225/79277542-df80b080-7e5e-11ea-9c75-95a19bf381ae.png)

error from console:
```
The FetchEvent for "https://covidtracking.com/data#state-ca" resulted in a network error response: an "opaqueredirect" type response was used for a request whose redirect mode is not "manual".
```

Android lts + Chrome lts

**Comment by kevee** [comment]
Tested and confirmed in browserstack: enter key works, but tapping a dropdown item throws an error. The FetchEvent is an unrelated Gatsby issue that isn't a problem.

**Comment by jasonlcrane** [comment]
I was poking around on this as well on my device. I don't see any related errors that are being thrown, but I think it's because the `jump-to-state` input retains focus on Android (in multiple browsers). Since that state picker element is not sticky on smaller screens, and the input is focused, the page quickly scrolls down to the hash where it should and then scrolls back up to the focused input. I poked through the [Combobox docs](https://reacttraining.com/reach-ui/combobox), source code and issues, but couldn't find anything relevant.

I _was_ able to fix this by blurring the `jump-to-state` field, but only with a slight delay in a setTimeout (50ms, so nothing noticable). Part of me hates to add that for everyone when it's only happening on Android (confirmed it's OK on iOS) or to add a device detection library to handle that. It might still be the best solution, though, and I have a PR ready to go and am happy to push it up if you want to take a look.

Another idea is to let that element be sticky for all screen sizes, so the page still scrolls to the right place, but the input of course will still be focused, and therefore the keyboard is enabled, which maybe we can live with. A little bit of CSS trickery will be necessary to position everything to correctly handle the height of the sticky element at various breakpoints.

Maybe there's a nicer React way to do this that I'm not familiar with, too, so I wanted to get this all out there and get other opinions.

**Comment by pspeter3** [comment]
I wonder if we can have state for the combo box being selected and then in `useLayoutEffect`; blur the combo box? Also can we pass a ref to the combobox so we don't need to find the element by the class name?
