### ISSUE TITLE
tooltip for 2 charts 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#574]
if we have time, we should add a tooltip for the sm multiples. this is the most important one, since we removed our y-axis labels 

we should also add one to the POSITIVE TESTS AND TOTAL TESTS IN THE US chart 

if this is complicated and we don't have time, let's add back the gridlines to the sm multiples and labels on the first chart of every row

**Comment by vijaysharwar** [comment]
@julialedur I don't think we can easily add the grid lines back to these. The charts are too small (the numbers will not be legible if displayed within the `AreaChart` instances). And it would be a high lift to add labels to each row, because the number of row items changes according to breakpoint. I also think it'll be tricky to convey y-axis values on the "Per Capita" charts.

For adding tooltips, what functionality is desired? Is it:

1. Single tooltip with just latest/current date's cumulative positive tests and positive tests, or...
2. Tooltip data changes as user hovers over different points along the x-axis?

For the "Per Capita" toggle/charts, the math currently just divides the number of tests by population. But that will be a very tiny decimal. So I think we need change it to "per one million people" (like the Bubble Map). It probably won't affect the visualization, since it's all relative. But probably best to calculate the data first, and use it for both tooltips and the charts.

**Comment by julialedur** [comment]
hey @vijaysharwar, 
i was thinking the second one! 

about per capita data, sounds good! we can round the numbers too 
thanks!

**Comment by julialedur** [comment]
fixed by [PR #642](https://github.com/COVID19Tracking/website/pull/642)

**Comment by kevee** [comment]
Closing per #642
