### ISSUE TITLE
stay-at-home line stroke-width

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#575]
in our sm multiples, we should make the line stroke for the stay-at-home orders the same in the chart and in the legend key (right now it's thicker on the legend) 

i suggest something in the middle of the two

**Comment by AaronMullan** [comment]
I will look at this.

**Comment by AaronMullan** [comment]
What I've found: 

The stroke of the annotations in the chart are set by strokeWidth to be 2px.  This is set in the area-chart.js file.  BUT the stroke re-scales depending on the width of the chart. So it's looking like at this chart width (750px) the stroke is thinner than it would otherwise be.  I can get it closer by changing the legend to 1px like this:

` &.chart-legend-stay-at-home {
    background-color: #000;
    height: 20px;
    margin: 0 14px 0 6px;
    vertical-align: middle;
    width: 1px;
  }`

**Comment by AaronMullan** [comment]
![Screen Shot 2020-04-15 at 4 13 14 PM](https://user-images.githubusercontent.com/50382381/79397968-4f149f80-7f34-11ea-95d5-18306fd0252a.png)

**Comment by julialedur** [comment]
awesome! thanks 😄 
could you also take care of [this issue](https://github.com/COVID19Tracking/website/issues/585) while you're at it @AaronMullan? 
super easy fix.
