### ISSUE TITLE
Please switch Press Links to a new spreadsheet

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#646]
I duped our press sheet and brought it into our new GSuite, could someone switch sources for our hompage and press links pages to this one? https://docs.google.com/spreadsheets/d/17KJTUTRwh-2og9Kx0OIZ4Ix5dm_51TL330wwgYSfTBs/edit?usp=sharing

Many thanks!

**Comment by schwartzadev** [comment]
Hey @webmasterkai I think this is your domain :smile:. Do you mind swapping this out?

**Comment by kissane** [comment]
Do we know where/how this happens? @kevee is this something you have eyes on?

**Comment by webmasterkai** [comment]
This is a private sheet. It would need to be made public. The API does not currently support getting data from private sheets. I'd recommend migrating it to Contentful instead of having it in a sheet. Moving to Contentful removes the need to have any API code related to press links. Press links seem to be more of a content item and less something that needs to be available in API form.

**Comment by webmasterkai** [comment]
Also, doesn't look like I have access to the sheet so changing code to work with private sheets wouldn't do us any good until we have a credentials token under the latest GSuite account https://console.developers.google.com/apis/credentials.

**Comment by kevee** [comment]
The sheet is public now.

**Comment by kissane** [comment]
Super happy to talk about what it would take to migrate to Contentful—the data is being collected in a Google Sheet by a team member's actual mom, so that's probably not going to change rn, but if we really need to copy things from her sheet to Contentful, I can ask someone to volunteer for that.
