### ISSUE TITLE
fix(dashboard): Change URL and put in the "How to Use It" subnavigation

### ISSUE THREAD

**Issue by jeremiak** [COVID19Tracking/website#672]
Right now the visual dashboard is available at `/dashboard`, but we'd like to make its target audience more clear by calling it "Visualization guide", changing the URL to `/about-data/visualization-guide` and adding it as a tab in the sub navigation for "How to Use It" such that the tabs would be
1. "How to Use the Data"
2. "Visualization guide"
3. "Newsroom FAQ"

**Comment by kissane** [comment]
I have done the parts of this that can be done in Contentful and now officially pass the baton to @kevee to adjust the custom page so that the Vis Guide page itself also shows the sub-nav tabs.

I also learned something about our Contentful setup, which is that for pages that use the CMS, we can't have Title Case in the nav and Sentence case on the page title itself, alas, it's one or the other. Let's change the title of the Vis Guide page to title case to match the rest of the site till Sara and I can discuss.
