### ISSUE TITLE
feat: Header redesign

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#738]
[Figma file](https://www.figma.com/file/fKUKsYMNw3NLSyIEOI1HKc/v2-refresh?node-id=353%3A3571)

- [x] Include work from `feature/search`
- [x] Add CTA
- [x] Add thin banner header
- [x] Add atlantic logo
- [x] Move navigation to right

**Comment by kevee** [comment]
Live preview here : https://feature-header-refresh--upbeat-lovelace-3e9fff.netlify.app/

**Comment by tealtan** [comment]
Some design notes here: (happy to move this elsewhere if it’s better)

The banner
- "New" should be `text-transform: uppercase` and not `font-variant: small-caps` so that all three letters are the same size.
- Can we left-align the banner text on mobile?
- The "New" and the banner link text should both be bolded.

The search and get involved buttons
- There should be about 6px less space between it and the nav items.
- The text should be smaller at 0.8rem (13px).
- I’ve changed the background color of the get involved button to be #ffffff. We can also remove the hover background color change.
- "Get Involved" the letter I should be uppercase, and it should be bold always (it is not bold on mobile currently).

"From The Atlantic"
- Can we adjust the "from" text to be smaller? It should be 0.625rem (10px). And for proper alignment, let’s set the margin to `0.2rem 0.75rem 0 0.75rem`.
- There should be about 0.5rem (8px) less space from the logo (on the whole div).
- The border looks like it’s 2px high in total, when it should be 1px – this can be changed by setting the border to 0.5px or by only setting a border-top of 1px.

The menu items on mobile
- Let’s make the spacing 1.75 between a) the search box and the menu items, b) the menu items from each other, c) above and below the get involved button.

**Comment by tealtan** [comment]
Two more notes on hover styling and then I think we’re good on everything minus the search!

- [ ] I’d like the banner text to have a hover color of #e2f1fc (which is what the nav items have)
- [ ] It looks like the Get Involved button text is picking up a generic hover style, so can we add something so that it stays the same #012656 color on hover?

**Comment by kevee** [comment]
Closed in #749
