### ISSUE TITLE
Large project

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#777]
✅ mobile
`components/pages/homepage/large-project.js`

**Comment by tealtan** [comment]
(Assuming this is the CRDT section)

- [ ] Can we adjust the border color to something lighter, such as `$color-slate-200`?
- [ ] The headline size should be bigger so that it looks like its own section – 36px on desktop, 24px on mobile.
- [ ] Can we tweak the color of the paragraph to be `$color-slate-700`?
- [ ] Let’s left-align the headline and paragraph for now.
- [ ] On desktop, the spacing between the CTA link and the end of the section can be cut in half. The current spacing for mobile looks good.

Thanks!!

**Comment by kevee** [comment]
@tealtan do you like the spacing on the top of the section? Just changed it to 120px on top, 60px on the bottom.

**Comment by tealtan** [comment]
Yep, looks great!
