### ISSUE TITLE
Header & big chart

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#778]
✅ mobile

**Comment by kevee** [comment]
We need to make the chart labels much bigger on mobile
![image](https://user-images.githubusercontent.com/270536/81086133-1da14b00-8ec6-11ea-8f1b-5c48ecc4880f.png)

**Comment by kevee** [comment]
To do:

- [ ] Remove legend on bottom
- [ ] Add color treatment to text like graphic below
- [ ] Make a mobile version of the chart that starts in March 1 and has larger labels

![image](https://user-images.githubusercontent.com/270536/81093303-e899f600-8ecf-11ea-8c8a-0fb0c6c1cbb7.png)

**Comment by julialedur** [comment]
This looks great! 🎉 a few suggestions: 

- I think the header needs to be the height of the screen, so it doesn't get cut off like this: 
<img width="1440" alt="Screen Shot 2020-05-05 at 12 49 47 PM" src="https://user-images.githubusercontent.com/39416238/81092766-1df21400-8ecf-11ea-8d74-d38cf809ad78.png">

- We can also delete the "CDC number vs our number" since we're already saying that in the text above the chart 

- @tealtan and I had talked about underlining the numbers in the text with the chart colors, so we have a legend in the text, like this: 

![v4](https://user-images.githubusercontent.com/39416238/81093059-8b9e4000-8ecf-11ea-8de6-d6d1f2f713f1.png)

- finally, I feel like the two chunks of text can be a bit narrower

**Comment by julialedur** [comment]
wow we're so in sync! 😂

**Comment by tealtan** [comment]
Yep, agreed with everything @julialedur and @kevee have said above.

Also, can we:
- [ ] Indent the headline and paragraph to start at the same place as the content below.
- [ ] Add a bit more space between the large headline and the chart (about 2rems-ish?).
- [ ] Change the headline size to be 1.75rem on mobile.
- [ ] Change the hero paragraph to 16px and not bold, so that it looks more like a caption. (On mobile it should be 13px)
- [ ] Change the text underlining from 5px to 3px.

**Comment by kevee** [comment]
I made the text wrap in a container the same size as the "Homepage container" so they line up. It does cause some wrapping but I think that's fine.

**Comment by kevee** [comment]
@julialedur - one question: I think we can't make the header the size of the screen just because there's so much stuff there with the text and chart that it won't fit. I played around with trying to make the header 1vh on a macbook pro and it didn't fit.

**Comment by julialedur** [comment]
hmmm have you tried making the chart a bit shorter and the text smaller? it might help to decrease the top margin between the main text and the nav bar too: 

<img width="1423" alt="Screen Shot 2020-05-05 at 4 40 00 PM" src="https://user-images.githubusercontent.com/39416238/81114062-3f62f800-8eef-11ea-943c-e48670becbd4.png">

**Comment by kevee** [comment]
Right, I could, the problem is the chart itself - it's a static SVG that if you change it's height dynamically will also make it shrink horizontally. Here it is on my computer with 1vh:

![image](https://user-images.githubusercontent.com/270536/81114688-83a2c800-8ef0-11ea-95a6-511a9e1139ef.png)

**Comment by kevee** [comment]
After merging #789, we now have text alignment issues since the chart pops up sooner.

![image](https://user-images.githubusercontent.com/270536/81116855-185af500-8ef4-11ea-93ea-d877758180bb.png)

**Comment by julialedur** [comment]
@jeremiak

**Comment by tealtan** [comment]
Could we scale down the chart on desktop so that it doesn’t span as wide?
