### ISSUE TITLE
Blog List

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#783]
Blog list
✅ mobile

**Comment by tealtan** [comment]
- [ ] This should have a top border like the other sections.
- [ ] On mobile, the byline contents are stacking vertically (they should stack horizontally and wrap as needed)
- [ ] The blog post title should be 1.125rem on mobile.
- [ ] Let’s left-align the section title for now.
- [ ] As on other sections, the section title should be 1.5rem on mobile.

May also have some spacing tweaks tk, will comment after you get through these since spacing may change.

Thanks!
