### ISSUE TITLE
change colors of the top for more contrast

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#807]
- as per @jasonsantamaria's suggestion, @tealtan and I came up with slightly different colors for the top to solve the issue of contrast. 

background color: plum600 #575AAD
CTP bars: honey500 #E2894E
CDC bars: plum100 #F2F2FF 

<img width="600" alt="Screen Shot 2020-05-06 at 5 02 04 PM" src="https://user-images.githubusercontent.com/39416238/81229384-b5ce2b80-8fbd-11ea-865e-0bd3c66ce84e.png">

- we also decided on a new treatment for the numbers, so they don't look like links: 
<img width="1147" alt="Screen Shot 2020-05-06 at 4 45 22 PM" src="https://user-images.githubusercontent.com/39416238/81229243-7d2e5200-8fbd-11ea-97a4-6e7d2f202cc8.png">

**Comment by kevee** [comment]
Got it! Question fo @tealtan this changes the color for the header site-wide, do we want to change the footer to match it?

**Comment by tealtan** [comment]
@kevee Yes, I’m good with changing the header and footer colors to match.

Also, Julia and I looked at the preview and had some additional tweaks:
- Let’s bold the highlighted numbers.
- Can we reduce the horizontal spacing between the bars on the chart a bit and increase their width a bit? (The gaps should look less wide than the bars)
- We’d also like to adjust the orange color since its saturation level is similar enough to the background that it’s a bit distracting. Can we try two colors? #F5853B (which is not in our palette, and would be a one-off) and #B6B7DB (in our palette, but not orange)
