### ISSUE TITLE
Feature request: embed @COVID19Tracking Twitter feed?

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#916]
Please let us know the page you are talking about, and your content suggestions!

I know it’s very 2010, but if the CTP Twitter account were embedded on the site somewhere it would often provide valuable context for each day’s numbers. Can haz?

**Comment by schwartzadev** [comment]
Are you thinking of a "latest tweets" dialog on the homepage?

I like this idea! @sarawb, what do you think?

**Comment by sarawb** [comment]
100% agree that the context and perspective on Twitter needs to get onto the site better! I don't love the idea of putting up latest tweets as the way to solve it, but I do want to think about what we are losing to the ephemeral stream by not capturing it in the context of the site.

**Comment by muamichali** [comment]
I think I suggested this before in an issue but not sure if anyone saw it.
What if we indexed the tweets as one of the types of content in search
results?

**Comment by kissane** [comment]
@amandafrench this is such a good issue to open. I think there are two kinds of content to deal with here: 

### Daily data tweets
The daily tweets are the closest thing we have to release notes for the daily data, so the most useful home for that information would be _right next to each day's update_. I think a link to the daily (pinned) tweet that begins the daily thread is probably the correct thing to bring onto the website, and my immediate thought is that each day's link should go right into the daily US update table row so that we have a historical archive of this context. I defer to @sarawb @tealtan @kevee on the specifics of display, but my own impression is that having tweets embedded is less important than linking to them and framing the link in helpful terms.

This raises a question about how to pipe them in—they come in AFTER the website build. We could actually manually drop those links into the spreadsheet/API/website pipeline, which would allow the tweets to be attached to the daily update for all data users, not just site users. There's some complexity about the timing, because the tweets don't get published until at least a few minutes after the daily website update drops, but I think that's probably OK. If the overall idea seems sound, we can run this through the data-layer-changes process, probably to run *after* we deal with probable COVID deaths and whatever happens with the ongoing people/specimens and serology situations.

### Regular tweets
I think most of the tweets that aren't about daily data releases are things that should turn into blog posts or that we don't actually _need_ to have on the site itself, but I'm very open to being wrong.

**Comment by kevee** [comment]
This all sounds great! Some thoughts:

1. A number of issues in our backlog are about speeding up page build times so we can do more deploys faster.
2. We can make the website ✨ **automatically** ✨  rebuild when the twitter account tweets, a specific hashtag would be even better.
3. There's [already a plugin](https://www.gatsbyjs.org/packages/gatsby-source-twitter/) we can use to pull all the tweets and display only the ones we want, using our style, so no like weird embedded iframe stuff.

**Comment by tealtan** [comment]
This is really smart – it makes a lot of sense to include the daily tweet update next to their daily data. 

Adding a link to the U.S. historical data table is easy enough (we will just need to think through what the link text should be in order to provide enough context, plus maybe add a Twitter icon next to it).

In light of Kevin’s link to pulling in tweets, I wonder if it’d be a good idea to save the daily tweet update on the website, for archival. That would mean coming up with a design and template for tweet threads, as well as any images and links those tweets have included.

**Comment by muamichali** [comment]
If we implement this, should the DE team add the link to the daily tweet somewhere so the web team will know which tweet to display on a given day? Or will it be handled programatically (ie first tweet on day x around 5pm)

**Comment by kevee** [comment]
It could be automagic, but we need a bit more strategy about this idea. We are starting to rethink the data pages in general, and I think incorporating this idea into that project is a good way to start.

**Comment by amandafrench** [comment]
I still think this is a good idea BTW though I don't know the best way to implement it technically or design-wise. :)
