### ISSUE TITLE
Design system: Forms

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#987]
[Figma file](https://www.figma.com/file/meG3i5VlD94qrTylsqZUXL/Library?node-id=28%3A3)

Let's create common components for all forms that aims for consistency and accessibility. There are already some components in `/src/components/common/forms`.

- [x] Create a single component for field groups (accepts a `label`, `isRequired`, and `field` component prop). Required fields get a readable 'required' label

This should then render something like:

```
<div class...>
<label for={id}>{label} <span>Required</span></label>
{children}
</div>
```

- [x] Create components for common input elements that use that field group. Something like:

```
const FormInput = ({type, name, label, isRequired, onChange}) => (
  <FormGroup label={label} isRequired={isRequired} id={name}>
  <input type={text} name={name} id={id} onChange={onChange}/>
</FormGroup>
)
```

Create one of these for:
- [x] Regular input field, with configurable `type` prop, i.e. `<FormInput type="text">` would render an `<input type="text">` in a field group.
- [x] Textarea
- [x] Radio & checkbox (maybe we just pass an array of values?)

- [x] We also need to pass events to these as well, let's do `onChange` for now. There is only one form that monitors inputs.

- [x] Support for half-width form groups

### Update forms:

- [x] Volunteer form
- [x] Contact form
- [x] Get involved form
- [x] Search page

**Comment by tiagofsanchez** [comment]
Think this could be something like this for the `input` component: 

```
const input = props => {
  const { inputtype, label } = props;

  let inputElement = null;
  switch (inputtype) {
    case "input":
      inputElement = <input className={inputStyle} {...props} />;
      break;
    case "text":
      inputElement = <textarea className={inputStyle} {...props} />;
//you can have as may cases you want here
      break;
    default:
      inputElement = <input sx={inputStyle} {...props} />;
  }

  return (
    <div className={theDivStyle}>
      <p className={theLabelStyle}>{label}</p>
      {inputElement}
    </div>
  );
};

```

Like this the Input component will be just <Input inputElement={input} onChange={changeHandler} />

Thoughts?

**Comment by tiagofsanchez** [comment]
Started to work on this and created a new branch [here](https://github.com/COVID19Tracking/website/tree/form-design-system). 

Would be great to have someone to review to make sure that it make sense and improves the current implementation. 

Changes made: 
- The FormInput now as a switch statement where we can defined the `inputElement` that we want, we could define anything here
- Also add the FormLabel details into the element so that whenever we want and to define and Input we only need 1 component instead of 2 and I believe we can also do that for FormGroup, but I will leave the Form component separate.  

Another thing we could do is move all the styling to the component itself whenever possible.

If this makes sense I can go and implement this approach on all forms that we have.

**Comment by tiagofsanchez** [comment]
@kevee, also modified the `Form` /src/components/common/forms component just now, in the same branch, so that we can use only 1 Form when we are designing any Form, e.g.
before:
```
<Form>
<form propshere ></form>
</Form>
```
now 
```
<Form propshere></Form
```
You can check this on the same branch with implementation on `get-involved/form` and `pages/contact/index` just to see if this was working properly... it seems that it is at my end.

**Comment by kevee** [comment]
@tiagofsanchez cool! I'm assigning this issue to you and creating a branch preview for your branch.

**Comment by tiagofsanchez** [comment]
@kevee, made same progress and should be finishing tonight... did you set up a branch preview? where can I see that? 
Thank you.
